# Generated by Django 5.1.2 on 2024-12-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lionzhd", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("series", "Series"), ("vod", "VOD")], max_length=10
                    ),
                ),
                ("stream_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("image", models.URLField()),
                ("added", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-added"],
            },
        ),
    ]
