# Generated by Django 5.1.2 on 2024-10-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lionzhd", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="XtreamConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "host",
                    models.CharField(default="http://xtream-codes.com", max_length=255),
                ),
                ("port", models.IntegerField(default=8080)),
                ("username", models.CharField(default="username", max_length=255)),
                ("password", models.CharField(default="password", max_length=255)),
                (
                    "meili_url",
                    models.CharField(default="http://umbrel:7700", max_length=255),
                ),
                ("meili_api_key", models.CharField(default="", max_length=255)),
            ],
        ),
    ]
