# Generated by Django 5.1.2 on 2025-01-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lionzhd", "0002_favoriteitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="xtreamconfig",
            name="user_agent",
            field=models.CharField(
                default="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0",
                max_length=1024,
            ),
        ),
    ]
